baseURL = ""
languageCode = "en-us"
title = "CeciLA Portafolio"
theme = "dream"


copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。'

googleAnalytics = "UA-98295641-1"

disqusShortname = "CeciLA"

enableRobotsTXT = true

hasCJKLanguage = true

# https://gohugo.io/news/0.60.0-relnotes/
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  background = "LAVENDER"
  backgroundImage = "/me/background.jpg"
  linkColor = "DARKMAGENTA"

  author = "Ceci L.A"
  description = "CeciLA Portafolio"
  avatar = "/me/yy.jpg"
  motto = "Este es mi portafolio"
  categories: ["category1"]
  tags: ["tag1", "tag2"]
  # showcase: true
  
  email = "cecila@gmail.com"
  twitter = "CeciLA"
  facebook = "CeciLA"
  instagram = "g1enyy0ung"
  linkedin = "钺杨CeciLA"
  github = "CeciLA"
  stackoverflow = "5676489/CeciLA"
  codepen = "CeciLA"

  siteStartYear = 2020

  favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "PLUM"
  darkNav = true
  dark404Button = true
